tasks:
  - init: |
      docker-compose pull
  - command: |
      sudo apt-get update
      pip install --upgrade pip
      pip install pyodbc
      sudo apt-get install odbcinst -y
      sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/21.10/prod impish main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
      sudo apt update
      sudo ACCEPT_EULA=Y apt install msodbcsql18 -y
      wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo gpg --dearmor -o /usr/share/keyrings/r-project.gpg
      echo "deb [signed-by=/usr/share/keyrings/r-project.gpg] https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" | sudo tee -a /etc/apt/sources.list.d/r-project.list
      sudo apt update
      sudo apt install --no-install-recommends r-base -y
      sudo apt install unixodbc-dev -y
      sudo Rscript -e 'install.packages("RODBC")'
      docker-compose up &
ports:
  - port: 1433
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - cmoog.sqlnotebook
    - mtxr.sqltools-driver-mssql
    - Mikhail-Arkhipov.r
    - REditorSupport.r
    - RDebugger.r-debugger
