tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 1433
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - cmoog.sqlnotebook
    - ms-mssql.mssql
