tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up &
      sudo apt-get update
      pip install --upgrade pip
      pip install pyodbc
      sudo apt-get install odbcinst
      sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/21.10/prod impish main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
      sudo apt update
      sudo ACCEPT_EULA=Y apt install msodbcsql18 -y
ports:
  - port: 1433
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - cmoog.sqlnotebook
    - mtxr.sqltools-driver-mssql
